apiVersion: apps/v1
kind: Deployment
metadata:
  name: promotion-deployment
  namespace: prod
  labels:
    app: promotion-service
spec:
  selector:
    matchLabels:
      app: promotion-service
  # 앱이 Ready 상태가 될 때까지 기다리는 시간
  minReadySeconds: 10
  # 롤링 업데이트:
  strategy:
    type: RollingUpdate
    rollingUpdate:
      # 롤링 업데이트시 스케일아웃할 최대 pod 수
      maxSurge: 1
      maxUnavailable: 0
  replicas: 1
  template:
    metadata:
      name: promotion-pod
      labels:
        app: promotion-service
    spec:
      containers:
        - name: promotion-service
          image: ${ECR_REGISTRY}/${AWS_ECR_REPOSITORY}:${IMAGE_TAG}
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 8084
          imagePullPolicy: IfNotPresent
          # 애플리케이션이 시작된 뒤 초기화 작업이 마무리되어 준비되었는지 검사
          readinessProbe:
            httpGet:
              path: /actuator/health/readiness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            httpGet:
              path: /actuator/health/liveness
              port: 8084
            initialDelaySeconds: 30
            periodSeconds: 30
            timeoutSeconds: 2
        - name: mysql
          image: mysql:8.0.34
          resources:
            requests:
              memory: "256Mi"
              cpu: "500m"
            limits:
              memory: "512Mi"
              cpu: "1000m"
          ports:
            - containerPort: 3306
          env:
            - name: MYSQL_ROOT_PASSWORD
              value: "11111111"
            - name: MYSQL_DATABASE
              value: promotion-service
            - name: LC_ALL
              value: C.UTF-8
          volumeMounts:
            - name: mysql-config
              mountPath: /etc/mysql/conf.d
            - name: promotion-ebs-pv
              mountPath: /var/lib/mysql
          imagePullPolicy: IfNotPresent
          # 애플리케이션이 시작된 뒤 초기화 작업이 마무리되어 준비되었는지 검사
          readinessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 20
          # 애플리케이션이 정상 상태를 유지하고 있는지 지속해서 검사
          livenessProbe:
            tcpSocket:
              port: 3306
            initialDelaySeconds: 20
            periodSeconds: 20
      volumes:
        - name: mysql-config
          configMap:
            name: mysql-config
        - name: promotion-ebs-pv
          persistentVolumeClaim:
            claimName: promotion-ebs-pvc
      # SIGTERM을 받아도 바로 종료되지 않고 90초 뒤에 종료
      terminationGracePeriodSeconds: 90
      restartPolicy: Always
      affinity:
        nodeAffinity:
          # Pod이 존재하지 않다가 처음으로 만들어지는 상태, 이미 실행중인데 nodeSelector가 node에서 제거된다면 계속 실행
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
              - matchExpressions:
                  - key: type
                    operator: In
                    values:
                      - App
                  - key: size
                    operator: In
                    values:
                      - Large
                      - Medium
