FROM amazoncorretto:11-alpine

WORKDIR /app

ENV PROFILES=dev

ARG ORIGINAL_JAR_FILE=./build/libs/promotion-service-1.0.0.jar

COPY ${ORIGINAL_JAR_FILE} promotion-service.jar

CMD ["java", "-Dspring.profiles.active=${PROFILES}", "-jar", "/app/promotion-service.jar"]
