spring:
  config:
    activate:
      on-profile: prod
    import: optional:configserver:http://config-service:8888

  # redis setting
  # TODO: redis settings cipher로 변경
  redis:
    host: 127.0.0.1
    port: 6379
    password: 11111111

  # rabbitmq settings
  rabbitmq:
    host: rabbitmq-service
    port: 5672
    username: guest
    password: guest
  # DB settings
  # dynamoDB 설정 추가 필요
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/promotion-service
    username: root
    password: 11111111
  # AWS DynamoDB settings 어떻게 될지 정해지지않아서 이렇게 두었음.
  data:
    dynamodb:
      endpoint: https://dynamodb.us-west-2.amazonaws.com # Use appropriate AWS Region
      region: us-west-2  # Use appropriate AWS Region
      access-key: access-key  # if not using environment variables or IAM
      secret-key: secret-key  # if not using environment variables or IAM
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://discovery-service:8761/eureka
  instance:
    instance-id: ${spring.application.name}:${server.port}
    # 기본적으로 유레카는 '호스트 이름'으로 접속하는 서비스를 레지스트리에 등록 -> 로컬(localhost)
    # 따라서 쿠버네티스, 도커와 같이 임의의 호스트 이름을 가지는 경우는 false로 하면 클라이언트를 인식하지 못한다.
    prefer-ip-address: true