server:
  port: 8084
spring:
  config:
    activate:
      on-profile: local,dev,prod
  application:
    name: promotion-service
management:
  endpoints:
    web:
      exposure:
        include: health, info, refresh, busrefresh